#!/bin/bash

usage() { echo "Usage: $0 [start | restart | stop]" 1>&2; exit 1; }

loadtables() {
    echo "running load tables"
    for file in ./database/defs/*.sql
    do
        psql -U lej -d draught_services -a -f $file -W password
    done

    for file in ./database/dumps/*.sql
    do
        psql -U lej -d draught_services -a -f $file -W password
    done
}

start() {
    if test -f ./.b_pids.tmp
    then
        rm ./.b_pids.tmp
    fi
    (
        cd ./api
        nohup node api_server.js &
        echo $! >> ../.b_pids.tmp
    ) > .api-start-log.tmp
    (
        cd ./ui
        nohup node ./node_modules/react-scripts/scripts/start.js &  
        echo $! >> ../.b_pids.tmp
    ) > .ui-start-log.tmp
    cat .api-start-log.tmp | cat .ui-start-log.tmp > start.log; rm .*log.tmp
}

stop() {
    if test -f ./.b_pids.tmp
    then
        cat .b_pids.tmp | xargs kill
        rm .b_pids.tmp
    fi
}

case $1 in
        start)
            #loadtables
            start
            ;;
        restart)
            stop
            #loadtables
            start
            ;;
        stop)
            stop
            ;;
        load)
            loadtables
            ;;
        *)
            usage
            ;;
esac

