#!/bin/bash

usage() { echo "Usage: $0 [start | restart | stop]" 1>&2; exit 1; }
start() {
    if test -f ./.b_pids.tmp
    then
        rm ./.b_pids.tmp
    fi
    (
        cd ./api
        nohup node ./node_modules/.bin/nodemon index.js &
        echo $! >> ../.b_pids.tmp
    ) > start.log
    (
        cd ./ui
        nohup node ./node_modules/react-scripts/scripts/start.js &  
        echo $! >> ../.b_pids.tmp
    ) > start.log
}
stop() {
    if test -f ./.b_pids.tmp
    then
        cat .b_pids.tmp | xargs kill
        rm .b_pids.tmp
    fi
}

case $1 in
        start)
            start
            ;;
        restart)
            stop
            start
            ;;
        stop)
            stop
            ;;
        *)
            usage
            ;;
esac

